### ISSUE TITLE
Add versioning to published Update Sites

### ISSUE THREAD

**Issue by abelgomez** [lhillah/pnmlframework#5]
Eclipse bundles for PNML framework are usually published in `http://pnml.lip6.fr/pnmlframework/updatesite/` as an Update Site.

However, only two update sites are available: "updatesite" and "updatesite-previous", whose contents may vary each time a new version is published.

Currently we have some tools that rely on PNML Framework (specifically 2.2.9), and the target platform specification expects to have PNML plugins published in an inmutable site. Could it be possible to give each version also a version-specific update site? Or at least, keep multiple versions (including the previous versions) in the same update?

Those update sites maybe published in the current external site, such as `http://pnml.lip6.fr/pnmlframework/updatesite/2.2.9/`, or better, using the gh-pages branch of this same GitHub repository (e.g.: `http://lhillah.github.io/pnmlframework/updates/2.2.9/`).

**Comment by lhillah** [comment]
The idea of the second suggestion sounds good to me. However, in that case, the developer will have to explicitly look for the new version instead of having it reminded by eclipse? 

Meanwhile, at least I can keep multiple versions in the same update site to comply with the immutable site requirement.

**Comment by abelgomez** [comment]
Hi @lhillah , you said:
> The idea of the second suggestion sounds good to me

Which second suggestion do you mean?

Regarding the possibility of a single update site with multiple versions is perfect too: if users don't care about the version, or if they want the latest one, that will be the one shown by default; if they prefer an older one, they can just show the previous ones and select them manually.

In fact, the single update site with multiple versions is the most transparent solution.

I just suggested to have multiple sites because it seemed easier to do if we want to make available again the versions published up to this moment.

**Comment by lhillah** [comment]
Dear Abel,

I will release the libraries as you suggested in multiple sites, like `http://pnml.lip6.fr/pnmlframework/updatesite/2.2.9/`. What I need to test is the config to aggregate them properly from the root of the update site. If there is not any proper means to do so so that the Eclipse update manager can pick them up, I'm afraid the user will have to explicitly point his update manager to the specific URL of a release.

Depending on Tycho and related tools, I could not aggregate and publish different releases under the same update site configuration, even though I configured the previous releases as dependencies from my public Nexus OSS repository (all artefacts of a release are also deployed in that repository), as explained in some discussion thread on SO (by the maintainer of Tycho).

So having multiple sites seems indeed easier to do.

Cheers.

**Comment by abelgomez** [comment]
Dear @lhillah ,

as I said at the beginning, having multiple sites instead of a single site is fine too. I imagined that this was the easiest solution :).

Thanks for addressing the issue. From my side, you can automatically close the issue once the site(s) are published (we need at least from 2.2.9).

Cheers!

**Comment by lhillah** [comment]
Hi @abelgomez,

For users who still want to be auto notified by a new update, we might keep the root /updatesite URI for them, so that their auto notification mechanism still works. 

Then, with specific /updatesite/X.Y.Z/ (including the latest that is in the root /updatesite) everyone will be using the version they wish for (either remain on a fixed version for compatibility and stability reasons, or use the new update flow for continuously upgrade to any fresh version).

What do you think about that?

Cheers

**Comment by abelgomez** [comment]
That's perfect :)

Thank you!

**Comment by lhillah** [comment]
Thanks for your feedback. Part of the configuration is already in place (i.e. /updatesite/X.Y.Z/, starting from 2.2.9). I will complete it today, and then close this issue.

Cheers!
